FROM python:3.10.15-slim AS samtools

ARG SAMTOOLSVER="1.17"

RUN apt-get update && apt-get install --no-install-recommends -y \
    libncurses5-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-gnutls-dev \
    zlib1g-dev \
    libssl-dev \
    gcc \
    wget \
    make \
    perl \
    bzip2 \
    gnuplot \
    ca-certificates \
    gawk

RUN wget https://github.com/samtools/samtools/releases/download/${SAMTOOLSVER}/samtools-${SAMTOOLSVER}.tar.bz2 && \
    tar -xjf samtools-${SAMTOOLSVER}.tar.bz2 && \
    rm samtools-${SAMTOOLSVER}.tar.bz2 && \
    cd samtools-${SAMTOOLSVER} && \
    ./configure && \
    make -j $(nproc) && \
    make install
   
FROM python:3.10.15-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    bcftools \
    tabix \
    bwa \
    procps && \
    apt-get autoclean && rm -rf /var/lib/apt/lists/*

COPY --from=samtools /usr/local/bin/samtools /usr/local/bin/

WORKDIR /parascopy
COPY . .

RUN python3 setup.py install

# Include licenses
COPY ["LICENSE", "./"]
COPY ["Third_Party_Licenses/", "./Third_Party_Licenses/"]
